require "options"
require "filetypes"
require "mappings"
require "autocmds"
require "lazyvim"

require "configs.lang.bash"
require "configs.lang.ccpp"
require "configs.lang.cmake"
require "configs.lang.css"
require "configs.lang.go"
require "configs.lang.html"
require "configs.lang.java"
require "configs.lang.json"
require "configs.lang.kotlin"
require "configs.lang.lua"
require "configs.lang.markdown"
require "configs.lang.php"
require "configs.lang.python"
require "configs.lang.rust"
require "configs.lang.sql"
require "configs.lang.tex"
require "configs.lang.toml"
require "configs.lang.ts-js"
require "configs.lang.xml"
require "configs.lang.yaml"

require("langmapper").automapping { buffer = false }
