vim.keymap.set({ "n" }, "<leader>lh", ":ClangdSwitchSourceHeader<CR>", { silent = true, desc = "Switch Source/Header" })
vim.keymap.set({ "n" }, "<leader>lH", ":ClangdTypeHierarchy<CR>", { silent = true, desc = "Type Hierarchy" })
vim.keymap.set({ "n" }, "<leader>lt", ":ClangdAST<CR>", { silent = true, desc = "Abstract Syntax Tree" })
vim.keymap.set({ "n" }, "<leader>ls", ":ClangdSymbolInfo<CR>", { silent = true, desc = "Symbol Info" })
vim.keymap.set({ "n" }, "<leader>lm", ":ClangdMemoryUsage<CR>", { silent = true, desc = "Memory Usage" })

vim.keymap.set({ "n" }, "<leader>lB", ":CMakeBuild<CR>", { silent = true, desc = "CMake Build Project" })
vim.keymap.set({ "n" }, "<leader>lR", ":CMakeRun<CR>", { silent = true, desc = "CMake Run Project" })
vim.keymap.set({ "n" }, "<leader>lD", ":CMakeDebug<CR>", { silent = true, desc = "CMake Debug Project" })
vim.keymap.set({ "n" }, "<leader>lT", ":CMakeRunTest<CR>", { silent = true, desc = "CMake Run Tests Project" })
vim.keymap.set({ "n" }, "<leader>lC", ":CMakeClean<CR>", { silent = true, desc = "CMake Clean Project" })
vim.keymap.set({ "n" }, "<leader>lW", ":CMakeOpen<CR>", { silent = true, desc = "CMake Open Executor/Terminal Window" })
