# Layout dwindle

# NOTE: pairs like:
# hyprctl keyword unbind modkey,key
# hyprctl keyword bind modkey,key,action


unbind = $mod, backslash
unbind = $mod SHIFT, backslash
bind = $mod, backslash, layoutmsg, togglesplit
bind = $mod SHIFT, backslash, layoutmsg, swapsplit
