# Layout scrolling (hyprscrolling plugin)

# NOTE: pairs like:
# hyprctl keyword unbind modkey,key
# hyprctl keyword bind modkey,key,action

unbind = $mod, H
unbind = $mod, J
unbind = $mod, K
unbind = $mod, L
bind = $mod, H, layoutmsg, focus l
bind = $mod, J, layoutmsg, focus d
bind = $mod, K, layoutmsg, focus u
bind = $mod, L, layoutmsg, focus r

unbind = $mod SHIFT, L
unbind = $mod SHIFT, H
bind = $mod SHIFT, L, layoutmsg, move +col
bind = $mod SHIFT, H, layoutmsg, move -col

unbind = $mod, left
unbind = $mod, right
bind = $mod, right, layoutmsg, swapcol r
bind = $mod, left, layoutmsg, swapcol l

unbind = $mod SHIFT, A
unbind = $mod SHIFT, E
unbind = $mod SHIFT, V
unbind = $mod SHIFT, B
unbind = $mod SHIFT, return
bind = $mod SHIFT, return, layoutmsg, fit all
bind = $mod SHIFT, V, layoutmsg, fit visible
bind = $mod SHIFT, E, layoutmsg, fit toend
bind = $mod SHIFT, B, layoutmsg, fit tobeg
bind = $mod SHIFT, A, layoutmsg, fit active

unbind = $mod, minus
unbind = $mod, equal
bind = $mod, minus, layoutmsg, colresize -conf
bind = $mod, equal, layoutmsg, colresize +conf

unbind = $mod, N
bind = $mod, N, layoutmsg, promote

unbind = $mod, backslash
bind = $mod, backslash, layoutmsg, togglefit
