#!/bin/env sh

# source: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories 
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"


# src: https://wiki.archlinux.org/title/Environment_variables#Default_programs
export SHELL="/usr/bin/zsh"
export EDITOR="nvim"
export SUDO_EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="firefox"
export PAGER="less"


# source: https://wiki.archlinux.org/title/Zsh#Startup/Shutdown_files
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export LF_CONFIG_HOME="$XDG_CONFIG_HOME"

export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GPG_TTY=$TTY

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

export JAVA_HOME="/usr/lib/jvm/java-23-openjdk"

export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"

export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc":"$XDG_CONFIG_HOME/gtk-2.0/gtkrc.mine"

export XCURSOR_PATH="${XCURSOR_PATH}:${XDG_DATA_HOME}/icons"

mkdir -p "$XDG_DATA_HOME"/wineprefixes
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

# oh-my-posh requirement
export PATH=$PATH:/home/a1pha/.local/bin

# Native file dialog for electron apps
export GTK_USE_PORTAL=1

export EZA_ICONS_AUTO=1
