[arch]
packages = [
  "hyprland",
  "hyprpicker",
  "hyprpolkitagent",
  "hyprshutdown",
  "hyprpwcenter",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-gtk",
  "qt5-wayland",
  "qt6-wayland",
  "wl-clipboard",
  "power-profiles-daemon",
  "nwg-displays",

  "udiskie",    # automount
  "ntfs-3g",
  "dosfstools", # ms-dos file-system formatting

  "grim",
  "slurp",
  "swappy",

  "acpi", # battery

  "brightnessctl",

  "networkmanager",
  "iwd",

  "mpd",

  "opentabletdriver",

  "qt5ct",
  "qt6ct",
  "nwg-look",
  "kvantum",
  "kvantum-theme-materia",
  "materia-gtk-theme",
  "papirus-icon-theme",
  "bibata-cursor-theme-bin",
  "adwaita-cursors",
  "adwaita-fonts",
  "adwaita-icon-theme",
  "sddm-conf",
  "catppuccin-sddm-theme-mocha",

  "ttf-jetbrains-mono-nerd",
  "ttf-roboto",
  "ttf-roboto-mono-nerd",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "ttf-dejavu",
  "ttf-liberation",
  "ttf-times-new-roman",

  "lxqt-config",
  "lxqt-admin",

  "paru",
  "paru-debug",
  "metapac",
  "nix",

  "wine",

  "stow",

  "kitty",

  "zsh",
  "fish",
  "fisher",
  "nushell",
  "starship",
  "fzf",
  "zoxide",
  "eza",
  "ripgrep",
  "fd",
  "bat",
  "less",
  "man",
  "tldr",
  "tree",

  "fastfetch",

  "btop",
  "nvtop",
  "neohtop",
  "resources",

  "net-tools",
  "bind",
  "netsleuth",

  "neovim",
  "luarocks",
  "tree-sitter-cli",
  "chafa",
  "viu",
  "ueberzugpp",
  "imagemagick",
  "libtexprintf",
  "python-pylatexenc",

  "opencode",

  "yazi",
  "ouch",
  "gvfs",
  "gvfs-mtp",
  "gvfs-afc",
  "gvfs-google-git",
  "gvfs-gphoto2",
  "gvfs-nfs",
  "gvfs-smb",
  "gvfs-dnssd",
  "gvfs-goa",
  "gvfs-onedrive",
  "gvfs-wsdd",
  "7zip",
  "trash-cli",
  "dragon-drop",

  "thunar",

  "gparted",
  "gnome-disk-utility",
  "xorg-xhost",

  "bluetui",

  "wiremix",
  "pavucontrol",
  "alsa-utils",

  "libreoffice-fresh",

  "okular",
  "pdfarranger",
  "img2pdf",

  "qbittorrent",

  "shotwell",
  "gwenview",
  "gimp",
  "inkscape",
  "krita",
  "drawio-desktop",
  "upscayl",
  "obs-studio",
  "kdenlive",
  "audacity",
  "handy",
  "mpv",

  "bitwarden",

  "v2rayn",
  "amneziavpn-bin",

  "syncthing",
  "localsend",

  "zen-browser-bin",
  "helium-browser-bin",

  # Git
  "git",
  "lazygit",
  "git-delta",

  # Docker
  "docker",
  "docker-compose",
  "lazydocker",

  # Kubernetes
  "kubectl",
  "k9s",
  "minikube",

  # DB
  "postgresql",
  "lazysql",
  "rainfrog",

  # Go
  "go",
  "golangci-lint",
  "goreleaser",

  # Python
  "python",
  "uv",
  "python-pipx",
  "quarto-cli-bin",
  "jupyter-notebook",
  "jupyter-nbconvert",
  "python-playwright",

  # Java
  # "jdk-openjdk",
  # "openjdk-doc",
  # "openjdk-src",
  # "maven",
  # "gradle",

  # C#, .NET
  # "dotnet-runtime",
  # "dotnet-sdk",
  # "dotnet-runtime-8.0",
  # "dotnet-sdk-8.0",
  # "aspnet-runtime",
  # "aspnet-targeting-pack",
  # "aspnet-runtime-8.0",
  # "aspnet-targeting-pack-8.0",

  # C/C++
  "gcc",
  "gdb",
  "cmake",
  "cmake-init-git",
  "conan",

  # LaTeX
  "texlive-latex",
  "texlive-fontsrecommended",
  "texlive-latexextra",
  "texlive-plaingeneric",
  "texlive-binextra",
  "biber",
]
