abbr nv='nvim'
abbr ff='fastfetch'
abbr sudonv='sudoedit'
abbr e="eza"
abbr ldoc='lazydocker'
abbr lgit='lazygit'
abbr da='date "+%Y-%m-%d %A %T %Z"'
abbr sha1='openssl sha1'
abbr kssh='kitty +kitten ssh'

abbr la='ls -l --almost-all --human-readable'
abbr lx='ls -l --sort=extension --ignore-backups --human-readable'
abbr lk='ls -l --sort=size --reverse --human-readable'
abbr lc='ls -l --sort=time --time=ctime --reverse --human-readable'
abbr lu='ls -l --sort=time --time=atime --reverse --human-readable'
abbr lr='ls -l --recursive --human-readable'
abbr lt='ls -l --sort=time --reverse --human-readable'
abbr lm='ls -l --all --human-readable | more'
abbr lw='ls -x --almost-all --human-readable'
abbr ll='ls -l --classify --size'
abbr labc='ls -l --all --indicator-style=slash'
abbr lf='ls -l | grep --invert-match "^d"'
abbr ldir='ls -l | grep "^d"'
abbr lla='ls -l --almost-all'
abbr las='ls --almost-all'
abbr lls='ls -l'

abbr mx='chmod a+x'
abbr 000='chmod --recursive 000'
abbr 644='chmod --recursive 644'
abbr 666='chmod --recursive 666'
abbr 755='chmod --recursive 755'
abbr 777='chmod --recursive 777'

abbr mktar='tar --create --verbose --file'
abbr mkbz2='tar --create --verbose --bzip2 --file'
abbr mkgz='tar --create --verbose --gzip --file'
abbr untar='tar --extract --verbose --file'
abbr unbz2='tar --extract --verbose --bzip2 --file'
abbr ungz='tar --extract --verbose --gzip --file'
