alias sudo='sudo '
alias fzf='fzf --preview "bat --color=always --style=numbers --line-range=:500 {}"'
alias pacman='pacman --color=always'
alias nv='nvim'
alias sudonv='sudoedit'
alias bat='bat --style=plain --pager=never'
# alias ls='ls --color=always'
alias ls='ls --classify --human-readable --color=always'
alias rg='rg --color=always'
# alias cdr='__zoxide_z'
alias cdr="__zoxide_zi"
alias ff='fastfetch'
alias eza='eza --color=always --icons=always'
alias e='eza'
alias ldoc='lazydocker'
alias lgit='lazygit'

alias da='date "+%Y-%m-%d %A %T %Z"'
alias cp='cp --interactive'
alias mv='mv --interactive'
alias trash='trash --verbose'
alias mkdir='mkdir --parents'
alias psall='ps auxf'
alias ping='ping --count 10'
alias less='less --RAW-CONTROL-CHARS'

source "$HOME/.config/sh/extended_aliases.sh"
