# See https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

#:schema = "https://yazi-rs.github.io/schemas/yazi.json"

[plugin]
prepend_fetchers = [
	{ url = "*", run = "git", group = "git" },
	{ url = "*/", run = "git", group = "git" },
]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch --show-file-icons" },
]

[input]
cursor_blink = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*", block = true, for = "windows" },
]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]

[mgr]
show_hidden = true
