return {
  "tpope/vim-fugitive",
  lazy = true,
  cmd = {
    "Git",
    "Gstatus",
    "Gcommit",
    "Gpush",
    "Gpull",
    "Gblame",
    "Gmerge",
    "Gdiffsplit",
    "Gvdiffsplit",
    "Gedit",
    "Gsplit",
    "Gread",
    "Gwrite",
    "Ggrep",
    "Glgrep",
    "Gmove",
    "Gdelete",
    "Gbrowse",
  },
  keys = {
    { mode = "n", "<leader>ga", "Git add", silent = true, desc = "Git Add" },
    { mode = "n", "<leader>gA", ":Git add .<CR>", silent = true, desc = "Git Add All" },
    { mode = "n", "<leader>gb", ":Git blame<CR>", silent = true, desc = "Git Blame" },
    { mode = "n", "<leader>gc", ":Git commit<CR>", silent = true, desc = "Git Commit" },
    { mode = "n", "<leader>gp", ":Git push<CR>", silent = true, desc = "Git Push" },
  },
}
