return {
  cmd = { "gopls" },
  settings = {
    gopls = {
      buildFlags = { "-tags=e2e" },
      gofumpt = true,
      completeUnimported = true,
      usePlaceholders = false,
      diagnosticsDelay = "250ms",
      staticcheck = true,
      analyses = {
        recursiveiter = true,
        maprange = true,
        framepointer = true,
        modernize = true,
        nilness = true,
        hostport = true,
        gofix = true,
        sigchanyzer = true,
        stdversion = true,
        unreachable = true,
        unusedfunc = true,
        unusedparams = true,
        unusedvariable = true,
        unusedwrite = true,
        useany = true,
      },
      codelenses = {
        test = true,
        gc_details = true,
        generate = true,
        run_govulncheck = true,
        tidy = true,
        upgrade_dependency = true,
        vendor = true,
      },
      hints = {
        compositeLiteralFields = true,
        parameterNames = true,
        constantValues = true,
        assignVariableTypes = true,
        functionTypeParameters = true,
        rangeVariableTypes = true,
        compositeLiteralTypes = true,
      },
    },
  },
}
