# See https://superfile.netlify.app/configure/superfile-config/

###############
### GENERAL ###
###############

theme = 'onedark'
editor = "" # "" - $EDITOR
dir_editor = "" # "" - default editor
auto_check_update = true
cd_on_quit = true # if true - update .<shell>rc
default_open_file_preview = true
show_image_preview = true
show_panel_footer_info = true
default_directory = "."
file_size_use_si = false # powers of 1000 (kB, MB, GB) instead of powers of 1024 (KiB, MiB, GiB)
default_sort_type = 0 # 0: Name, 1: Size, 2: Date Modified, 3: Type
sort_order_reversed = false # false: Ascending, true: Descending
case_sensitive_sort = false
shell_close_on_success = false
debug = false
ignore_missing_fields = false


#############
### STYLE ###
#############

code_previewer = 'bat' # "" - chroma
nerdfont = true
transparent_background = false
file_preview_width = 0 # 0 - same as file panel | [2;10]
sidebar_width = 20 # 0 - disable | [3;20]
border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'


###############
### PLUGINS ###
###############

metadata = true # requirement: exitfull
enable_md5_checksum = false
zoxide_support = true # requirement: zoxide
