# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'l']
quit = ['ctrl+c', 'q', 'esc']
# movement
list_up = ['up', 'k']
list_down = ['down', 'j']
page_up = ['pgup','ctrl+u']
page_down = ['pgdown','ctrl+d']
# file panel control
create_new_file_panel = ['ctrl+t', '']
close_file_panel = ['ctrl+w', '']
next_file_panel = ['tab', ']', '']
previous_file_panel = ['shift+tab', '[', '']
toggle_file_preview_panel = ['ctrl+l', '']
open_sort_options_menu = ['s', '']
toggle_reverse_sort = ['S', '']
# change focus
focus_on_process_bar = ['ctrl+p', '']
focus_on_sidebar = ['ctrl+s', '']
focus_on_metadata = ['ctrl+i', '']
# create file/directory and rename
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['y', '']
cut_items = ['x', '']
paste_items = ['p', '']
delete_items = ['d', '']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# other
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
copy_path = ['Y', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['ctrl+f', '']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['esc', 'ctrl+q']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['backspace', 'h']
search_bar = ['/', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['J', '']
file_panel_select_mode_items_select_up = ['K', '']
file_panel_select_all_items = ['A', '']
