[general]
fullscreen = false          # false | "all" | "current-screen"
resize = { mode = "smart" } # mode = "smart" | mode = "size", width = 2000, height = 800
floating-hack = true        # try to have the window float
auto-copy = false

# Exit directly after copy/save action
early-exit = [] # "copy" | "save" | "save-as" | "all"

corner-roundness = 12
initial-tool = "brush" # "pointer" | "crop" | "line" | "arrow" | "rectangle" | "text" | "marker" | "blur" | "brush"

copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "~/Media/Pictures/Screenshots/screenshot-%Y-%m-%d_%H:%M:%S.png"
save-after-copy = false
default-hide-toolbars = false
focus-toggles-toolbars = false
default-fill-shapes = false
primary-highlighter = "block"
disable-notifications = false

# actions (order is important): "save-to-clipboard" | "save-to-file" | "save-to-file-as" | "copy-filepath-to-clipboard" | "exit"
actions-on-right-click = []
actions-on-enter = ["save-to-clipboard"]
actions-on-escape = ["exit"]

no-window-decoration = true
brush-smooth-history-size = 10
pan-step-size = 50.0           # The pan step size to use when panning with arrow keys.
zoom-factor = 1.1
text-move-length = 50.0        # The length to move the text when using arrow keys
input-scale = 1.0

[keybinds]
pointer = "p"
crop = "c"
brush = "b"
line = "i"
arrow = "z"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "u"
highlight = "g"

[font]
family = "Roboto"
style = "Regular"

[color-palette]
palette = ["#f0932bff", "#eb4d4bff", "#6ab04cff", "#22a6b3ff", "#130f40FF"]

# Leave empty to use GTK's default
custom = [
    # "#a52a2a",
    # "#ffd700",
    # "#008000",
]
